### PR TITLE
Fix for Registration UX bug

### PR DESCRIPTION
**Pull request by RommelTJ**
### Reference Ticket

https://github.com/matterinc/PeepethClient/issues/5

### Description

Fix for Registration UX bug. When user types in a password, the "Passwords don't match" label shows up because the `textField:shouldChangeCharactersIn` function is matching the text with the `nil` text of the `repeatPasswordTextField`. This PR solves that issue simply by hiding the `passwordsDontMatch` label whenever `repeatPasswordTextField.text?.isEmpty`.

### Changes

- [x] Adding extra check in `CreateWalletViewController` for when `repeatPasswordTextField` is empty.

### Review

- [ ] @BaldyAsh, code review, EOD 10/06
- [ ] @skywinder, code review, EOD 10/06

### CODE REVIEW

**Comment by skywinder** [comment]
Thanks! That works.

just a question about storyboard changes. What does it do? should it be there?

**Comment by RommelTJ** [comment]
Thanks, @skywinder.  The storyboard changes can be safely ignored. I opened the storyboard to find out which view controller was the correct one to modify. When I did that, Xcode automatically modifies the file. I didn't alter anything in the storyboard, just opened it. This is a fairly annoying issue when working with storyboard files in Xcode using git in a team environment as multiple factors such as monitor resolution, retina vs non-retina displays, etc change the positioning of the frames ever so slightly. 

If it really bothers you, I can open up a second PR with the storyboard changes removed. Going forward, I can make sure these type of storyboard changes are not committed.

**Comment by BaldyAsh** [comment]
@skywinder yeah storyboard isn't a good decision - we'll remove it in future. Can't you just make commit here without it? If you make the commit in yours branch - it will also be here

**Comment by RommelTJ** [comment]
@BaldyAsh Well, it was a single commit, so I'll have to roll it back and commit again for a total of 3 commits (let me know if there's a better way). The git history would be a bit cleaner if I just open a new PR, but that's ok. I'll remove the storyboard change when I get home. 👍

**Comment by RommelTJ** [comment]
@BaldyAsh @skywinder Storyboard changes have been removed.

**Comment by BaldyAsh** [comment]
@RommelTJ Hooray 🙌Thank you for your work and interest in our project! I hope to see you again 🔥And have fun Hacktoberfesting 🎃

**Pull request merged**
